### ISSUE TITLE
Add header to child's settings

### ISSUE THREAD

**Issue by romgerman** [citizenll/godot-flexbox#17]
Hello. It would be a great to have a header of child's settings and to have the settings placed after child's script block.
This is current behavior:
![image](https://github.com/citizenll/godot-flexbox/assets/1517367/074564f7-9a2c-49cd-b0c5-606c9c22d846)

**Comment by citizenll** [comment]
This suggestion is feasible, and will be included in the upcoming update plan.

**Comment by citizenll** [comment]
The functionality support has been updated but not released in the current version. If needed, please retrieve it from the code repository. 
e01804e2b053006a11d4a0898340e3ef5584c38b
