### ISSUE TITLE
Flexbox not declared in current scope

### ISSUE THREAD

**Issue by Mikeysax** [citizenll/godot-flexbox#2]
![image](https://user-images.githubusercontent.com/15805689/235354154-6ab32edf-a9b5-4d5c-85ae-58d8b99023e3.png)

```
res://addons/godot-flexbox/flex_container.gd:97 - Parse Error: Identifier "Flexbox" not declared in the current scope.
  Cannot save GDScript file 'res://addons/godot-flex/plugin.gd'.
  res://addons/godot-flexbox/flex_container.gd:51 - Parse Error: Identifier "Flexbox" not declared in the current scope.
  res://addons/godot-flexbox/flex_container.gd:96 - Parse Error: Identifier "Flexbox" not declared in the current scope.
  Cannot save GDScript file 'res://addons/godot-flex/plugin.gd'.
  not enough arguments for format string
  platform/windows/os_windows.cpp:391 - Method/function failed. Returning: ERR_CANT_OPEN
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: C:/Users/Micha/Documents/Code/Transcription/addons/godot-flexbox/bin/windows/libgdflexbox.x86_64.dll
  Failed loading resource: res://addons/godot-flexbox/flexbox.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

**Comment by drewdus42** [comment]
Same issue for me on Godot 4.0.1 and 4.0.2

**Comment by citizenll** [comment]
@trekfan42 @Mikeysax 
Please check if the plugin is enabled in the project settings. If it is not enabled, please restart the project after enabling it.

>Project/Project Settings/Plugins -> Enable Plugin


![image](https://user-images.githubusercontent.com/16896067/236230738-566ab0a9-6c0a-42a7-b04a-ff83c0161664.png)


It's work on my  4.0.2
![image](https://user-images.githubusercontent.com/16896067/236230864-f55ce048-3836-4b32-8239-c53351478956.png)

**Comment by VikingAntics** [comment]
That did not work.  It seems to be looking for libgdflexbox.x86_64.dll which is not in the repository or the installation.  I think.

**Comment by citizenll** [comment]
> That did not work. It seems to be looking for libgdflexbox.x86_64.dll which is not in the repository or the installation. I think.

If you are trying to clone this repository and run the demo project, you need to download the release file and extract it to the addons folder, which includes the libgdflexbox.x86_64.dll file.
The path will be like *addons/godot-flexbox/*
