### ISSUE TITLE
Error message and empty flexbox

### ISSUE THREAD

**Issue by Azeler-3** [citizenll/godot-flexbox#4]
After installation (both by using the AssetLib or cloning the directory) and at repeated intervals afterwards, the following error message appears :

"Error loading extension: res://addons/godot-flexbox/flexbox.gdextension"

Enabling the addon is possible (only after cloning the directory directly), but a FlexContainer node just appears as a control node with the flex_container.gd script, with no visible parameters.

The script itself has two error messages from Flexbox not being declared in the scope.

Godot version : 4.1 stable release

**Comment by Azeler-3** [comment]
I just realised the 4.1 version is still in WIP, not the latest release. I misread the README, sorry for the inconvenience.

**Comment by citizenll** [comment]
The latest binary file has been delayed in construction for a while. I have identified the issue and am preparing to rebuild the release file.
