### ISSUE TITLE
Error loading extension when downloading directly from "Assetlib" in the godot client.

### ISSUE THREAD

**Issue by Zentarg** [citizenll/godot-flexbox#5]
When downloading directly from the assetlib, I get the following error:
![image](https://github.com/citizenll/godot-flexbox/assets/22545419/dec25848-7e89-4e5a-b1c6-538bbdb900fd)
This seems to be caused by the missing "compatibility_minimum" parameter:
![image](https://github.com/citizenll/godot-flexbox/assets/22545419/c9274ced-27d2-4e76-8de6-a10bcea81f8b)

However even after adding that to the .gdextension (`compatibility_minimum = 4.1.0`), I get the following error:
![image](https://github.com/citizenll/godot-flexbox/assets/22545419/014a555e-d50f-47a8-8e5e-8057737d3b11)
(I have made sure to check that the .dll file exists at that path, and it does)

Observed using Windows 11, and godot v4.1.1

**Comment by Zentarg** [comment]
I forgot to mention that when I set "compatibility_minimum" to "4.1", godot just downright crashes (And will not re-launch unless I change it back)

**Comment by citizenll** [comment]
The latest binary file has been delayed in construction for a while. I have identified the issue and am preparing to rebuild the release file.

**Comment by citizenll** [comment]
The latest binary file release version has been published
