### ISSUE TITLE
It doesn't work example code.

### ISSUE THREAD

**Issue by cplus98** [citizenll/godot-flexbox#9]
Godot 4.1.2 and godot-flexbox 2.0 were used.
When the following code is executed.

```
extends Control

func _ready():
	var root = Flexbox.new()
	root.set_width(500)
	root.set_height(300)
	
	var child = Flexbox.new()
	child.set_min_width(100)
	child.set_min_height(100)
	root.insert_child(child, 0)
		
	root.calculate_layout(NAN,NAN,1)
	
	print(root.get_computed_layout())
```

It shows the following output: 
```
{ “left”: nan, “right”: nan, “top”: nan, “bottom”: nan, “width”: nan, “height”: nan }
{ “left”: nan, “right”: nan, “top”: nan, “bottom”: nan, “width”: nan, “height”: nan }
```

The result of the layout calculation is incorrect.

**Comment by citizenll** [comment]
I'm glad you are able to try the basic API. This is the result of your code that I just tried, and it seems to be as expected. I also don't know what the situation is on your side 😲.
![image](https://github.com/citizenll/godot-flexbox/assets/16896067/9e58498d-22d7-4d16-a493-7a1baa6bb6d8)

**Comment by cplus98** [comment]
![Screenshot 2023-10-23 at 1 07 23 PM](https://github.com/citizenll/godot-flexbox/assets/40209639/9e62a40f-7b35-4c1b-9fad-25a112706bea)

I'm using M2 Mac.
Could it be that it doesn’t work with Apple silicon?

**Comment by citizenll** [comment]
Oh, actually I am using Windows. I don't have a Mac at the moment😔. The library file of the project is built with GitHub Actions. I don't have much feedback on whether it runs successfully on other platforms. Another platform where I have successfully run it is Android.
If you know how to build GDExtension, please feel free to submit a PR to solve this problem. I would be extremely grateful.
Thank you again for your feedback❤️.

**Comment by cplus98** [comment]
I just build this library with python scons on my mac. Without modify any codes.
It works well with newly built library!

![Screenshot 2023-10-23 at 9 32 01 PM](https://github.com/citizenll/godot-flexbox/assets/40209639/62f7f227-8469-4a57-8416-8ea0c46a6685)
![Screenshot 2023-10-23 at 9 35 04 PM](https://github.com/citizenll/godot-flexbox/assets/40209639/d98b93cd-567a-42da-b026-97c8b9d8dd27)

You may need to try adjusting this project's build options for apple silicon processor (M1 higher).
I don't know how to use Guthub Actions so it's hard to give any other advice.
Thanks!

**Comment by citizenll** [comment]
> I just build this library with python scons on my mac. Without modify any codes. It works well with newly built library!
> 
> ![Screenshot 2023-10-23 at 9 32 01 PM](https://user-images.githubusercontent.com/40209639/277336639-62f7f227-8469-4a57-8416-8ea0c46a6685.png) ![Screenshot 2023-10-23 at 9 35 04 PM](https://user-images.githubusercontent.com/40209639/277340022-d98b93cd-567a-42da-b026-97c8b9d8dd27.png)
> 
> You may need to try adjusting this project's build options for apple silicon processor (M1 higher). I don't know how to use Guthub Actions so it's hard to give any other advice. Thanks!

This is a pleased outcome. Thank you so much for your effort. I will try to add M1 platform build options in Github Actions.

**Comment by cplus98** [comment]
I found something about this.

Perhaps I built it in debug mode without the target option.
`scons -j12`

If you add "target=release" to the same build option as the library, the same error occurs.
`scons -j12 target=release`

I don’t know why it only works in debug mode library.

--------------------------------------

I solved this problem. :)
Optimize option changed.
I'll pull request.
